### PR TITLE
[SERV-812] Ignore empty metadata elements

### PR DESCRIPTION
**Pull request by markmatney**
- Make harvester fail
- Filter out empty elements :hole:

### CODE REVIEW

**Review by ksclarke — DISMISSED** [review]
Are there fields that are required? So, for instance, if there was only an empty date field but date was a required field.

**Comment by markmatney** [comment]
I don't have a very good answer to that question in the general sense, but for date in particular: we have been provided records without dates in the past, and those have been harvested to the current system; it's not ideal, but it doesn't break anything in a disastrous way, IMO. So my inclination would be to continue not requiring it.

**Comment by ksclarke** [comment]
Yes, I was thinking more in the general sense, given our conversation -- do we know what things are required, in addition to which values are required to match certain patterns (which I know you've done), etc. (e.g., are there things that are required if another one/element is present, etc.?)

**Comment by markmatney** [comment]
Each metadata field is independent in that the presence of one doesn't have any bearing on whether another must be present. However, we do have a metadata guidelines document which specifies certain fields as required and others as optional. According to it, date _is_ a required field, however there was never any specification as to what the behavior of the system should be if it is absent. The current implementation (the one we are replacing) takes the stance: allow it to be missing.

**Comment by ksclarke** [comment]
Is the current system inheriting the stance of the previous system?

**Comment by markmatney** [comment]
The other "required" fields are title and creator.

**Comment by markmatney** [comment]
I don't see why we should exclude records that don't have a date. Perhaps there is other metadata in such a record that is valuable to someone. The "PM" way back when wanted a fancier date facet UI than what we got (some sort of timeline with sliders or something), and I think that may have been the motivation behind "requiring" date.

**Review by ksclarke — APPROVED** [review]

**Comment by markmatney** [comment]
Let's discuss this at the next team meeting?

**Review by DRickard — APPROVED** [review]

**Pull request merged**
