### PR TITLE
[SERV-492] Update project skeleton

### PR DESCRIPTION
**Pull request by markmatney**
- Rename Vert.x Template to PRL Harvester
- Use recommended naming scheme for OpenAPI spec
- Upgrade to JUnit 5
- Rewrite MainVerticle
- Rough out Dockerfile

### CODE REVIEW

**Comment by markmatney** [comment]
I guess we also need GitHub Actions. I can add that here too unless that should be a separate ticket.

**Review by DRickard — APPROVED** [review]

**Review by ksclarke — CHANGES_REQUESTED** [review]
Did my review as a PR - https://github.com/UCLALibrary/prl-harvester/pull/2

**Comment by ksclarke** [comment]
> I guess we also need GitHub Actions. I can add that here too unless that should be a separate ticket.

Up to you... either way sounds good to me.

**Review by ksclarke — APPROVED** [review]

**Comment by markmatney** [comment]
@cachemeoutside can you review my removal of the Helm chart part (see last commit)? If that step is appropriate for this project, I can revert + copy over the Helm Maven Plugin config from the libcal-proxy pom.xml as well.

**Comment by cachemeoutside** [comment]
I'd say lets add it back in since we don't really have capacity to look into Pulumi at this point

**Review by cachemeoutside — APPROVED** [review]
Helm portion looks good to me. I'll add the helm secrets on Monday in the repo config.

**Pull request merged**
