### PR TITLE
[SERV-584] Configure Solr index for data retrieval

### PR DESCRIPTION
**Pull request by markmatney**
I essentially ported [the old schema and config](https://github.com/UCLALibrary/prrla-solr-conf) to the new Solr configuration API syntax. I have spun up a front-end locally and confirmed that data retrieval works, but search does not.

### CODE REVIEW

**Comment by markmatney** [comment]
So the build is failing due to lines in one of the shell scripts being longer than 120 chars. Should we make an exception for this file?

**Comment by ksclarke** [comment]
> So the build is failing due to lines in one of the shell scripts being longer than 120 chars. Should we make an exception for this file?

I actually meant to ask you about that shell script but looking at this PR now I _think_ I might know the answer. Was curious why you didn't write the configuration in Java since there is a Java API and it would fit in better with our tests. I'm guessing now it's because you were doing the setup through this extra container and didn't want to install Java on it and going through a build, etc. when you could just use the shell script?

**Comment by markmatney** [comment]
I wasn't aware there was a Java SDK; do you have a link to it?

**Comment by ksclarke** [comment]
I haven't done this myself since I last used Solr when it preferred config files, but I guess I just _assumed_ that, if they're providing an HTTP API and deprecating editing the files, they've also incorporated it into their official SDKs, too(!) -- not to say one couldn't do the same thing you're doing through curl with a plain Java HTTP client.

Glancing at the Javadocs (i.e., not looking deeply, so I could be mistaken), is this not what we need for the schema? https://solr.apache.org/docs/9_0_0/solrj/org/apache/solr/client/solrj/request/schema/package-summary.html and https://solr.apache.org/docs/9_0_0/solrj/org/apache/solr/client/solrj/request/ConfigSetAdminRequest.html for the configsets?

**Comment by markmatney** [comment]
Turns out I was mistaken about the Schema and Config APIs being the preferred way to configure Solr; I've changed it back to the config file setup.

Search still isn't working, so I have created SERV-595 for fixing that.

**Review by ksclarke — DISMISSED** [review]

**Review by DRickard — DISMISSED** [review]

**Review by ksclarke — APPROVED** [review]

**Review by DRickard — APPROVED** [review]

**Pull request merged**
